version: '3.9'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: wizybot.postgres
    ports:
      - 5432:5432
    networks:
      - mi-red
    environment:
      - POSTGRES_USER=wizyuser
      - POSTGRES_PASSWORD=wizypassword
      - POSTGRES_DB=wizydatabase

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-servidor
    ports:
      - 7000:7000
    env_file:
      - .env
    networks:
      - mi-red
    depends_on:
      - postgres

networks:
  mi-red:
    driver: bridge
